### ISSUE TITLE
Velemeny

### ISSUE THREAD

**Issue by kebeleicsaba** [Teaching-projects/SOE-ProgAlap1-Beadando-Kebelei-Csaba#1]
Hali! Pontosan igazabal annyit tudnek, mondani, hogy mire nezz ra, hogy mennyisegben meg bonyolultsagban, illetve kivitelezesben (sikerult-e a fuggvenyeket logikusan szetszednem) elegendo-e kodom. Viszont nekem ez nem egy surgos dolog.

**Comment by hegyhati** [comment]
Most teljesen melyen nem neztem at a dolgokat, de ami a lenyeg:
 - a leiras szuper, bar egy-ket gameplay screenshot azert feldobna.
 -  meg nem probaltam ki a jatekot, de feltetelezve, hogy mukodik, szuper
 - gondolkodj el azon, hogy mik azok a fuggvenyek, amiket ki lehetne modulba szedni, es amennyire lehet (de meg ertelmes) szedd szet. Gondolok itt arra, hogy pl nem egy fajlban van valoszinuleg a helye annak a figgvenynek, ami a snake fejet mozgatja, meg annak, ami egy menut ir ki, vagy epp kimenti az eredmenyeket. 
 - A fuggvenyekhez legyen pdoc dokumentacio, ez legyen is legeneralva, es az is felcommitolva a repoba.
 
 Most igy ezek, szolj ha megvannak, es akkor melyebben atnezem a kodot. 
 
 Szep amugy, nem lesz nagyon kerdeses az erdemjegy.

**Comment by kebeleicsaba** [comment]
Szia!
Befejeztem a változtatásokat, amiket kértél.

**Comment by hegyhati** [comment]
Kezdjuk azzal, hogy megvan az otos, ez nem kerdes, szep munka!

Par dolog van, amit lehetne csinositani, mint pl:
 - A `stat.py` szep, hogy kulon van szedve, de a `Clear` miatt "berantod" a `game`-et. Nyilvan ez igy kisse overkill
 -  Kicsit tovabbvive: a `Game`-ben pl a Clear nem passzol logikailag oda, hiszen annak a terminalos moszerolas a feladata, semmi koze a jatekhoz. Ugyanigy a `NickName` is egy olyan dolog, ami igazabol meg a terminalos felulen ker user inputot. Ilyen szempontbol logikailag kozelebb all a stat vagy main reszekhez. 
 - Tobbszor van olyan, hogy egy fuggvenynek igy adsz at parametereket: `PrintSnake(snake["body"], snake["head"], game["score"], screen, black)`. A fuggvenyek argumentumjainak szamat altalaban igyekezzuk minel kisebbkent kezelni, ennek tobb oka is van. Szoval ez szebb lenne pl igy: `PrintSnake(snake, game["score"], screen, black))` (Ha masolnank, ez lehetne lassabb, de python ugye nem igy mukodik) 
 
 De ezek aprosagok, es abszolut nem lvl1 programming kerdesek. Nomeg az objektumorientaltsag sok ilyesmit megold.
 
 Technikai dolog: akkor vedd fel a kovetkezo vizsgat, mas dolgod nincs, en meg beirom a **jeles**t.

**Comment by kebeleicsaba** [comment]
Wow, köszönöm szépen!
